all:
  hosts:
    hardened-server:
      ansible_host: 172.18.0.2
      ansible_user: ansible
      ansible_port: 2222
      ansible_ssh_private_key_file: /root/.ssh/id_ed25519
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: ""
